#!/bin/bash
#INPUT
#S: bam file name (without .bam extention)
#CHRSIZE: reference genome chromosome sizes (list of: chrXX size)
#MAPQ: Min read MAPQ (recommended 5)
#CHRS: array of chr names. E.g. CHRS=(1 2 3 4) chromosomes not included in the list will be skipped
#D: Directory with containing the bam files
#OUTPUT
#chrCoverageMedians_ File with chromosome name, median nucleotide coverage, and +/- 2 MADs
S=$1
CHRSIZE=$2
MAPQ=$3
CHRSstr=$4
D=$5


IFS=' ' read -r -a CHRS <<< $CHRSstr  

#estimate the median coverage +/- 2 MADs (median absolute deviation)
echo -e "CHR\tMEDIANCOV\tMEDIANCOVminus2MAD\tMEDIANCOVplus2MAD" > ${D}/chrCoverageMedians_$S
for CHR in "${CHRS[@]}"; do 
    samtools depth -a -Q $MAPQ ${D}/${S}.bam -r $CHR > ${D}/_notNormalized_chrCoverageMediansNoGaps$S
    mkdir -p ${D}/TMPsortDir_notNormalized_$S
    MEDIANCOV=`cut -f3 ${D}/_notNormalized_chrCoverageMediansNoGaps$S | sort -n -T ${D}/TMPsortDir_notNormalized_$S |  awk ' { a[i++]=$1; } END { x=int((i+1)/2); if (x < (i+1)/2) print (a[x-1]+a[x])/2; else print a[x-1]; }'`
    MAD=`awk 'function abs(x){return ((x < 0.0) ? -x : x)}  {dev=abs($4 - '$MEDIANCOV'); print dev }' ${D}/_notNormalized_chrCoverageMediansNoGaps$S | sort -n -T ${D}/TMPsortDir_notNormalized_$S |  awk ' { a[i++]=$1; } END { x=int((i+1)/2); if (x < (i+1)/2) print (a[x-1]+a[x])/2; else print a[x-1]; }'`
    maxDp=`perl -e 'print '$MEDIANCOV'+ (2 * '$MAD');'`
    minDp=`perl -e 'print '$MEDIANCOV'- (2 * '$MAD');'`
    rm -rf  ${D}/TMPsortDir_notNormalized_$S ${D}/_notNormalized_chrCoverageMediansNoGaps$S
    echo -e "$CHR\t$MEDIANCOV\t$minDp\t$maxDp" >> ${D}/chrCoverageMedians_$S
done

