#!/bin/bash
#############################################################################
# giptools                                                                  #
#                                                                           #
# Authors: Giovanni Bussotti                                                #
# Copyright (c) 2021  Institut Pasteur                                      #
#                                                                           #
#                                                                           #
# This program is free software: you can redistribute it and/or modify      #
# it under the terms of the GNU General Public License as                   #
# published by the Free Software Foundation, either version 3 of the        #
# License, or (at your option) any later version.                           #
#                                                                           #
# This program is distributed in the hope that it will be useful,           #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with this program.  If not, see <https://www.gnu.org/licenses/>.    #
#                                                                           #
#############################################################################

########
#OUTPUT#
########
#.covPerGe file normalized by chromosome median coverage    
#######
#INPUT#
#######
#A chromosome median coverage file (chrCoverageMedians file, syntax: chrXX median .* ) and a covPerBin file (syntax: chr start end meanCoverage)
#NOTE1: the input covPerGe file need to be not normalized before this function
#NOTE2: covPerBin input windows that are not on the chromosomes in the chrCoverageMedians file are removed from the output

CHRM=$1
COVPERGE=$2
OUT=$3

perl -e '
open(C,"<'$CHRM'");
while(<C>){
  if($_=~/^(\S+)\s+(\S+)/){$chr=$1;$m=$2; $mCovs{$chr} = $m;}
}
close C;

open(O,">'$OUT'");
open(F,"<'$COVPERGE'");
$header = <F>;
chomp $header;
print O "$header\t"."normalizedMeanCoverage\n";
while(<F>){
  if ($_=~/^(\S+)\s+(\S+)\s+(\S+)/){
    $gene_id=$1;
    $locus=$2;
    $meanCoverage=$3;
    if ($locus=~/^([^\:]+):([^\-]+)-(\S+)/){
    	$chr=$1;$st=$2;$en=$3;
    } else {die "covPerGe_normalizedByChrMedianCov cannot parse locus $locus";}                     
    next if(! defined $mCovs{$chr});
    $normMean   = $meanCoverage / $mCovs{$chr};
    print O "$gene_id\t$locus\t$meanCoverage\t$normMean\n";      
  }
}
close F;
close O;'

