#!/bin/bash
########
#OUTPUT#
########
#.covPerGe file normalized by chromosome median coverage    
#######
#INPUT#
#######
#A chromosome median coverage file (chrCoverageMedians file, syntax: chrXX median .* ) and a covPerBin file (syntax: chr start end meanCoverage)
#NOTE1: the input covPerGe file need to be not normalized before this function
#NOTE2: covPerBin input windows that are not on the chromosomes in the chrCoverageMedians file are removed from the output

CHRM=$1
COVPERGE=$2
OUT=$3

perl -e '
open(C,"<'$CHRM'");
while(<C>){
  if($_=~/^(\S+)\s+(\S+)/){$chr=$1;$m=$2; $mCovs{$chr} = $m;}
}
close C;

open(O,">'$OUT'");
open(F,"<'$COVPERGE'");
$header = <F>;
chomp $header;
print O "$header\t"."normalizedMeanCoverage\n";
while(<F>){
  if ($_=~/^(\S+)\s+(\S+)\s+(\S+)/){
    $gene_id=$1;
    $locus=$2;
    $meanCoverage=$3;
    if ($locus=~/^([^\:]+):([^\-]+)-(\S+)/){
    	$chr=$1;$st=$2;$en=$3;
    } else {die "covPerGe_normalizedByChrMedianCov cannot parse locus $locus";}                     
    next if(! defined $mCovs{$chr});
    $normMean   = $meanCoverage / $mCovs{$chr};
    print O "$gene_id\t$locus\t$meanCoverage\t$normMean\n";      
  }
}
close F;
close O;'

