#!/bin/bash
#############################################################################
# giptools                                                                  #
#                                                                           #
# Authors: Giovanni Bussotti                                                #
# Copyright (c) 2021  Institut Pasteur                                      #
#                                                                           #
#                                                                           #
# This program is free software: you can redistribute it and/or modify      #
# it under the terms of the GNU General Public License as                   #
# published by the Free Software Foundation, either version 3 of the        #
# License, or (at your option) any later version.                           #
#                                                                           #
# This program is distributed in the hope that it will be useful,           #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with this program.  If not, see <https://www.gnu.org/licenses/>.    #
#                                                                           #
#############################################################################

########
#OUTPUT#
########
#.covPerBin file normalized by chromosome median coverage    
#######
#INPUT#
#######
#A chromosome median coverage file (chrCoverageMedians file, syntax: chrXX median .* ) and a covPerBin file (syntax: chr start end meanCoverage)
#NOTE1: the input covPerBin file need to be not normalized before this function
#NOTE2: covPerBin input windows that are not on the chromosomes in the chrCoverageMedians file are removed from the output

CHRM=$1
GCOVBIN=$2
OUT=$3

perl -e '
   open(C,"<'$CHRM'");
   while(<C>){
           if($_=~/^(\S+)\s+(\S+)/){$chr=$1;$m=$2; $mCovs{$chr} = $m;}
   }
   close C;

   open(O,">'$OUT'");
   open(F,"<'$GCOVBIN'");
   $header = <F>;
   chomp $header;
   print O "$header\t"."normalizedMeanCoverage\n";
   while(<F>){
           if ($_=~/^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/){
                   $chr=$1;
                   $start=$2;
                   $end=$3;
                   $mean=$4;
                   
                   next if(! defined $mCovs{$chr});
                   $normMean   = $mean / $mCovs{$chr};
                   print O "$chr\t$start\t$end\t$mean\t$normMean\n";      
           }
   }
   close F;
   close O;
'
