#!/bin/bash
########
#OUTPUT#
########
#.covPerBin file normalized by chromosome median coverage    
#######
#INPUT#
#######
#A chromosome median coverage file (chrCoverageMedians file, syntax: chrXX median .* ) and a covPerBin file (syntax: chr start end meanCoverage)
#NOTE1: the input covPerBin file need to be not normalized before this function
#NOTE2: covPerBin input windows that are not on the chromosomes in the chrCoverageMedians file are removed from the output

CHRM=$1
GCOVBIN=$2
OUT=$3

perl -e '
   open(C,"<'$CHRM'");
   while(<C>){
           if($_=~/^(\S+)\s+(\S+)/){$chr=$1;$m=$2; $mCovs{$chr} = $m;}
   }
   close C;

   open(O,">'$OUT'");
   open(F,"<'$GCOVBIN'");
   $header = <F>;
   chomp $header;
   print O "$header\t"."normalizedMeanCoverage\n";
   while(<F>){
           if ($_=~/^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/){
                   $chr=$1;
                   $start=$2;
                   $end=$3;
                   $mean=$4;
                   
                   next if(! defined $mCovs{$chr});
                   $normMean   = $mean / $mCovs{$chr};
                   print O "$chr\t$start\t$end\t$mean\t$normMean\n";      
           }
   }
   close F;
   close O;
'
