#!/bin/bash
IN=$1
OUT=$2
minNormCovForDUP=$3
maxNormCovForDEL=$4
SAMPLE_ID=$5
DF=$6

BED=$DF/${IN}.bed
COV=$DF/coverages/${IN}.cov 
gunzip ${COV}.gz
SV=`echo ${OUT: -7} | cut -f1 -d "."`
echo "#cmd: filterByCov BED is $BED ;;; COV is $COV ;;; SV is $SV" 
echo -e "locus\tnormCov\tpercReadsSupportingSV\tMAPQ\tSV\tsampleId\tSVid" > $OUT
perl -e '
open(F,"<'$COV'") or die "error opening COV\n";
$_=<F>;
while(<F>){
    if($_=~/^\S+\s+(\S+)\s+\S+\s+(\S+)\s+(\S+)/){
        $locus   = $1;
        $normCov = sprintf("%.2f",$2);
        $MAPQ    = sprintf("%.2f",$3);
        $h{$locus}{"normCov"} = $normCov;
        $h{$locus}{"MAPQ"}    = $MAPQ;
    }
}
close F;
open(F,"<'$BED'") or die "error opening BED\n";
while(<F>){
    if($_=~/^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/){
        $locus=$1 . ":" . $2 . "-" . $3;
        $h{$locus}{"SVid"} = $4;
        $h{$locus}{"percReadsSupportingSV"} = $5;
    }
}
close F;
foreach $locus (sort { $h{$b}->{"normCov"} <=> $h{$a}->{"normCov"}} keys %h){
    if (! defined $h{$locus}{"normCov"}){"die error in filterByCov\n";};
    $normCov = $h{$locus}{"normCov"};
    $MAPQ    = $h{$locus}{"MAPQ"} ;
    $SVid    = $h{$locus}{"SVid"};
    $percReadsSupportingSV = $h{$locus}{"percReadsSupportingSV"};
    if(('$SV' eq "DUP")&&($normCov < '$minNormCovForDUP')){next;}
    if(('$SV' eq "DEL")&&($normCov > '$maxNormCovForDEL')){next;}
    print "$locus\t$normCov\t$percReadsSupportingSV\t$MAPQ\t'$SV'\t'$SAMPLE_ID'\t$SVid\n";
}' >> $OUT

