packages <- list(
"ape", 
"argparse", 
"Biostrings", 
"data.table", 
"FactoMineR", 
"fastcluster", 
"Genomiges" ,
"ggExtra" ,
"ggplot2" ,
"gplots" ,
"heatmap3", 
"IRanges" ,
"RColorBrewer", 
"reshape2" ,
"scales" ,
"seqLogo" ,
"unbalhaar" ,
"VariantAnnotation" ,
"entropy" ,
"fitdistrplus" ,
"gtools" ,
"igraph" ,
"MCL" ,
"mclust", 
"mixtools", 
"networkD3" ,
"psych" ,
"session" ,
"ggridges" ,
"bisoreg",
"bootstrap" ,
"monreg" ,
"R2WinBUGS", 
"coda"
)
package.load.check <- sapply(packages, require, character.only = TRUE)
if (!all(package.load.check)) stop("Not all packages loaded")
